spring:
  datasource:
    password: MySQL123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?useSSL=true&useUnicode=true&characterEncoding=UTF-8

    # 配置 druid 和监控功能
    druid:
      stat-view-servlet:
        enabled: true # 启用
        login-username: rainbowsea  # 用户名
        login-password: 123   # 密码
        reset-enable: false  # true 表示开启  druid 监控功能

      # 配置 Web监控
      web-stat-filter:
        enabled: true  # 启用
        url-pattern: /*  # 监视所有
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"  # 排除过滤不监视的内容

      # 配置 sql监控 和 SQl防火墙，都是在过滤器当中的
      filter:
        stat: # sql监控
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true # 开启
          # 配置 SQl 防火墙
        wall:
          config:
            alter-table-allow: false
#            select-all-column-allow: false
            drop-table-allow: false
          enabled: true
