server:
  port: 9090  # 注意：使用空格

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL123
    url: jdbc:mysql://localhost:3306/springboot_mybatis?useSSL=true&useUnicode=true&characterEncoding=UTF-8

mybatis:
  # 指定要扫描的 Xxxmapper.xml
  mapper-locations: classpath:mapper/*.xml


  # 通过config-location 可以指定mybatis-config.xml 可以以传统的方式来配置mybatis
#  config-location:
# 我们可以直接在 application.yaml 进行配置
# 举例说明1，比如配置原来的 typeAliases
  # 还有很多配置，等我们用到再说
#  type-aliases-package: com.rainbowsea.springboot.mybatis.bean
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true

# 老师说明: 配置mybatis的两种方式的选择: 如果配置比较简单，就直接在application.yaml配置
# 如配置内部比较多，可以考虑单独的做一个mybatis-config.xml