server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_mybatis?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL123


mybatis-plus:
  configuration:  # 进行mybatis-puls配置，配置项和mybatis是一样的 开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
