spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true # 开启页面表单的rest功能，启用了HiddenHttpMethodFilter,支持rest
    view: # 配置视图解析器
      prefix: /rainbowsea/** # 这里是需要注意，如果你配置了 static-path-pattern: /rainbowsea/** 需要保持一致
#      prefix: /rainbowsea/ 都行 # 这里是需要注意，如果你配置了 static-path-pattern: /rainbowsea/** 需要保持一致
      suffix: .html

    static-path-pattern: /rainbowsea/**
